### ISSUE TITLE
Datum/Zeit Format

### ISSUE THREAD

**Issue by philomat** [DRK-Odenwaldkreis/Zeiterfassung#1]
Wir sollten uns auf ein Format für die Zeitstempel in der Datenbank einigen. Mir ist es eben beim Rumspielen schon ein paar mal passiert, dass ich nicht kompatible Formate gewählt habe. Ich würde daher folgendes vorschlagen:

`"%Y-%m-%d %H:%M:%S" `

im Python Jargon bedeutet dass z.B.

2021-01-05 16:05:00

Milli- und Mikrosekunden werden wir nicht brauchen. Sekunden wahrscheinlich schon, da wir ja eine Sperrzeit für Buchungen am Terminal haben wollen. Und mit dem Format kommen wir auch nicht in irgendwelche Formatierungschwierigkeiten.

Was meint ihr?

**Comment by mbay-ODW** [comment]
Wie im Beispiel des Terminals zu sehen ist nutze ich ebenfalls dieses Zeitformat:


2021-01-06 20:48:05

So setzt es aktuelle auch die MySQL Datenbank von alleine wenn ich nichts übergebe. Passt also für mich. Marc hat aber hinsichtlich "parsing" mehr zu tun.

**Comment by mbay-ODW** [comment]
Done
