### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by mbay-ODW** [DRK-Odenwaldkreis/Zeiterfassung#2]
Ich werde innerhalb des Terminals mit den normalen Logleveln arbeiten und in ein Textfile schreiben.
Wollen wir diese Logs irgendwie Serverseitig zur Verfügung stellen? Irgendwelche Ideen?

**Comment by marc-DA** [comment]
Du meinst sowas wie alle X Min. mal hochladen und wir haben Zugriff und können aus der Ferne schon Fehler finden? Gute Idee. Logs zeitlich begrenzen auf nur die letzten 24h?

**Comment by mbay-ODW** [comment]
Ja genau. Stündlich würd ja reichen vermutlich. Transportweg wäre zu klären.

**Comment by marc-DA** [comment]
FTP?

**Comment by mbay-ODW** [comment]
Mh ja, guter Punkt. Dann schreib ich .log files und synce den kompletten ordner mit cron.
