### ISSUE TITLE
Backup Database SQLite auf Terminal PC

### ISSUE THREAD

**Issue by mbay-ODW** [DRK-Odenwaldkreis/Zeiterfassung#4]
Ich schreibe jedes Scanevent nochmals in eine SQLite Datenbank auf dem Laptop. Hierfür wähle ich lediglich die Struktur:

id, hash, timestamp

Auf die Art können wir später quasi per batch events nach scannen.
Allerdings gibt es wohl unter python3 keine sinnvolle möglichkeit die sqlite Datenbank passwort zu sichern. 

Wie wollen wir damit umgehen? Aus den Hash´s alleine lässt sich nichts Personenbezogen ableiten.

**Comment by marc-DA** [comment]
Wir haben auf dem Terminal PC dann Hash und Timestamp gespeichert, wobei der Terminal PC nicht von außen erreichbar ist. Also Zugriff nur von Personen mit direktem Hardware-Zugriff. Ich wäre okay damit.

**Comment by mbay-ODW** [comment]
Genau, Hardware-Zugriff wäre notwendig und Liste der Hashs´s gegen Personalnummern vom Server.
