### ISSUE TITLE
UI Änderungen überschneiden sich wenn after() genutzt wird

### ISSUE THREAD

**Issue by mbay-ODW** [DRK-Odenwaldkreis/Zeiterfassung#8]
Ich nutze für die TKinter komponenten die Funktion after(), bei der er quasi UI Komponenten nach einer Zeit eine Änderung durchführt. Allerdings kann sich das überlappen wenn man innerhalb dieses after() nochmal was macht. Heißt also wenn ich mit after() anstoße das der Bildschirm nach 1000ms resetet wird (Weil dann die Anzeige KOMMEN weg sein soll), gleichzeitig aber ein neuer Mitarbeiter scannt (Und ein GEHEN bekommt), dann wird das GEHEN direkt nach der after() Zeit vom KOMMEN resetet.

Hab keine Idee wie ich das lösen soll ohne mit sleeps zu arbeiten, die dann den Ablauf auch blockieren.

**Comment by marc-DA** [comment]
Nur ein paar Ideen ohne Gewähr auf Ausführbarkeit:
Kannst du die Anzeige auslagern und den timestamp zur Meldung mit ablegen. Die Anzeige holt sich die Meldung aus einem Speicher.
Ein extra Job läuft jede 1s durch und leert das Display, wenn die Anzeigemeldung älter als 5 s ist.
Sollte in den 5 s eine neue Anzeigemeldung kommen, wird die bestehende überschrieben mit neuem timestamp. Ist die Anzeige schon leer, wird eben "leer" oder die Meldung "Bitte Ausweis scannen" überschrieben.

**Comment by mbay-ODW** [comment]
Gefunden über after_cancel(). Muss ich mir zwar die after ID merken und global speichern aber hat geklappt. Ist im main drin!
